//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkateFactory2.WebUI.SkateboardService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Skateboard", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Skateboard : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private float WeightField;
        
        private SkateFactory2.WebUI.SkateboardService.EColor ColorField;
        
        private SkateFactory2.WebUI.SkateboardService.ESkateType SkateTypeField;
        
        private SkateFactory2.WebUI.SkateboardService.EBrakeType BrakeTypeField;
        
        private SkateFactory2.WebUI.SkateboardService.EShapeType ShapeTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public SkateFactory2.WebUI.SkateboardService.EColor Color {
            get {
                return this.ColorField;
            }
            set {
                if ((this.ColorField.Equals(value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public SkateFactory2.WebUI.SkateboardService.ESkateType SkateType {
            get {
                return this.SkateTypeField;
            }
            set {
                if ((this.SkateTypeField.Equals(value) != true)) {
                    this.SkateTypeField = value;
                    this.RaisePropertyChanged("SkateType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public SkateFactory2.WebUI.SkateboardService.EBrakeType BrakeType {
            get {
                return this.BrakeTypeField;
            }
            set {
                if ((this.BrakeTypeField.Equals(value) != true)) {
                    this.BrakeTypeField = value;
                    this.RaisePropertyChanged("BrakeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public SkateFactory2.WebUI.SkateboardService.EShapeType ShapeType {
            get {
                return this.ShapeTypeField;
            }
            set {
                if ((this.ShapeTypeField.Equals(value) != true)) {
                    this.ShapeTypeField = value;
                    this.RaisePropertyChanged("ShapeType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EColor", Namespace="http://tempuri.org/")]
    public enum EColor : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Undefined = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Blue = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Green = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Red = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ESkateType", Namespace="http://tempuri.org/")]
    public enum ESkateType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Undefined = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Electric = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Regular = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EBrakeType", Namespace="http://tempuri.org/")]
    public enum EBrakeType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Undefined = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Dynamic = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Friction = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EShapeType", Namespace="http://tempuri.org/")]
    public enum EShapeType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Undefined = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Plastic = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Wood = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ESkateboardCriteria", Namespace="http://tempuri.org/")]
    public enum ESkateboardCriteria : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Electric = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Regular = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SkateboardService.SkateboardServiceSoap")]
    public interface SkateboardServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        SkateFactory2.WebUI.SkateboardService.HelloWorldResponse HelloWorld(SkateFactory2.WebUI.SkateboardService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<SkateFactory2.WebUI.SkateboardService.HelloWorldResponse> HelloWorldAsync(SkateFactory2.WebUI.SkateboardService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name skateboard from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        SkateFactory2.WebUI.SkateboardService.InsertResponse Insert(SkateFactory2.WebUI.SkateboardService.InsertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        System.Threading.Tasks.Task<SkateFactory2.WebUI.SkateboardService.InsertResponse> InsertAsync(SkateFactory2.WebUI.SkateboardService.InsertRequest request);
        
        // CODEGEN: Generating message contract since element name skateboard from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        SkateFactory2.WebUI.SkateboardService.UpdateResponse Update(SkateFactory2.WebUI.SkateboardService.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<SkateFactory2.WebUI.SkateboardService.UpdateResponse> UpdateAsync(SkateFactory2.WebUI.SkateboardService.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        void Delete(int skateboardId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteAsync(int skateboardId);
        
        // CODEGEN: Generating message contract since element name GetListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetList", ReplyAction="*")]
        SkateFactory2.WebUI.SkateboardService.GetListResponse GetList(SkateFactory2.WebUI.SkateboardService.GetListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetList", ReplyAction="*")]
        System.Threading.Tasks.Task<SkateFactory2.WebUI.SkateboardService.GetListResponse> GetListAsync(SkateFactory2.WebUI.SkateboardService.GetListRequest request);
        
        // CODEGEN: Generating message contract since element name SearchByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchById", ReplyAction="*")]
        SkateFactory2.WebUI.SkateboardService.SearchByIdResponse SearchById(SkateFactory2.WebUI.SkateboardService.SearchByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchById", ReplyAction="*")]
        System.Threading.Tasks.Task<SkateFactory2.WebUI.SkateboardService.SearchByIdResponse> SearchByIdAsync(SkateFactory2.WebUI.SkateboardService.SearchByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public SkateFactory2.WebUI.SkateboardService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(SkateFactory2.WebUI.SkateboardService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public SkateFactory2.WebUI.SkateboardService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(SkateFactory2.WebUI.SkateboardService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert", Namespace="http://tempuri.org/", Order=0)]
        public SkateFactory2.WebUI.SkateboardService.InsertRequestBody Body;
        
        public InsertRequest() {
        }
        
        public InsertRequest(SkateFactory2.WebUI.SkateboardService.InsertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SkateFactory2.WebUI.SkateboardService.Skateboard skateboard;
        
        public InsertRequestBody() {
        }
        
        public InsertRequestBody(SkateFactory2.WebUI.SkateboardService.Skateboard skateboard) {
            this.skateboard = skateboard;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertResponse", Namespace="http://tempuri.org/", Order=0)]
        public SkateFactory2.WebUI.SkateboardService.InsertResponseBody Body;
        
        public InsertResponse() {
        }
        
        public InsertResponse(SkateFactory2.WebUI.SkateboardService.InsertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertResponseBody {
        
        public InsertResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public SkateFactory2.WebUI.SkateboardService.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(SkateFactory2.WebUI.SkateboardService.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SkateFactory2.WebUI.SkateboardService.Skateboard skateboard;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(SkateFactory2.WebUI.SkateboardService.Skateboard skateboard) {
            this.skateboard = skateboard;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public SkateFactory2.WebUI.SkateboardService.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(SkateFactory2.WebUI.SkateboardService.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateResponseBody {
        
        public UpdateResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetList", Namespace="http://tempuri.org/", Order=0)]
        public SkateFactory2.WebUI.SkateboardService.GetListRequestBody Body;
        
        public GetListRequest() {
        }
        
        public GetListRequest(SkateFactory2.WebUI.SkateboardService.GetListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public SkateFactory2.WebUI.SkateboardService.ESkateboardCriteria criteria;
        
        public GetListRequestBody() {
        }
        
        public GetListRequestBody(SkateFactory2.WebUI.SkateboardService.ESkateboardCriteria criteria) {
            this.criteria = criteria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListResponse", Namespace="http://tempuri.org/", Order=0)]
        public SkateFactory2.WebUI.SkateboardService.GetListResponseBody Body;
        
        public GetListResponse() {
        }
        
        public GetListResponse(SkateFactory2.WebUI.SkateboardService.GetListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SkateFactory2.WebUI.SkateboardService.Skateboard[] GetListResult;
        
        public GetListResponseBody() {
        }
        
        public GetListResponseBody(SkateFactory2.WebUI.SkateboardService.Skateboard[] GetListResult) {
            this.GetListResult = GetListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchById", Namespace="http://tempuri.org/", Order=0)]
        public SkateFactory2.WebUI.SkateboardService.SearchByIdRequestBody Body;
        
        public SearchByIdRequest() {
        }
        
        public SearchByIdRequest(SkateFactory2.WebUI.SkateboardService.SearchByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int skateboardId;
        
        public SearchByIdRequestBody() {
        }
        
        public SearchByIdRequestBody(int skateboardId) {
            this.skateboardId = skateboardId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public SkateFactory2.WebUI.SkateboardService.SearchByIdResponseBody Body;
        
        public SearchByIdResponse() {
        }
        
        public SearchByIdResponse(SkateFactory2.WebUI.SkateboardService.SearchByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SkateFactory2.WebUI.SkateboardService.Skateboard SearchByIdResult;
        
        public SearchByIdResponseBody() {
        }
        
        public SearchByIdResponseBody(SkateFactory2.WebUI.SkateboardService.Skateboard SearchByIdResult) {
            this.SearchByIdResult = SearchByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SkateboardServiceSoapChannel : SkateFactory2.WebUI.SkateboardService.SkateboardServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SkateboardServiceSoapClient : System.ServiceModel.ClientBase<SkateFactory2.WebUI.SkateboardService.SkateboardServiceSoap>, SkateFactory2.WebUI.SkateboardService.SkateboardServiceSoap {
        
        public SkateboardServiceSoapClient() {
        }
        
        public SkateboardServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SkateboardServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SkateboardServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SkateboardServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SkateFactory2.WebUI.SkateboardService.HelloWorldResponse SkateFactory2.WebUI.SkateboardService.SkateboardServiceSoap.HelloWorld(SkateFactory2.WebUI.SkateboardService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            SkateFactory2.WebUI.SkateboardService.HelloWorldRequest inValue = new SkateFactory2.WebUI.SkateboardService.HelloWorldRequest();
            inValue.Body = new SkateFactory2.WebUI.SkateboardService.HelloWorldRequestBody();
            SkateFactory2.WebUI.SkateboardService.HelloWorldResponse retVal = ((SkateFactory2.WebUI.SkateboardService.SkateboardServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SkateFactory2.WebUI.SkateboardService.HelloWorldResponse> SkateFactory2.WebUI.SkateboardService.SkateboardServiceSoap.HelloWorldAsync(SkateFactory2.WebUI.SkateboardService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<SkateFactory2.WebUI.SkateboardService.HelloWorldResponse> HelloWorldAsync() {
            SkateFactory2.WebUI.SkateboardService.HelloWorldRequest inValue = new SkateFactory2.WebUI.SkateboardService.HelloWorldRequest();
            inValue.Body = new SkateFactory2.WebUI.SkateboardService.HelloWorldRequestBody();
            return ((SkateFactory2.WebUI.SkateboardService.SkateboardServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SkateFactory2.WebUI.SkateboardService.InsertResponse SkateFactory2.WebUI.SkateboardService.SkateboardServiceSoap.Insert(SkateFactory2.WebUI.SkateboardService.InsertRequest request) {
            return base.Channel.Insert(request);
        }
        
        public void Insert(SkateFactory2.WebUI.SkateboardService.Skateboard skateboard) {
            SkateFactory2.WebUI.SkateboardService.InsertRequest inValue = new SkateFactory2.WebUI.SkateboardService.InsertRequest();
            inValue.Body = new SkateFactory2.WebUI.SkateboardService.InsertRequestBody();
            inValue.Body.skateboard = skateboard;
            SkateFactory2.WebUI.SkateboardService.InsertResponse retVal = ((SkateFactory2.WebUI.SkateboardService.SkateboardServiceSoap)(this)).Insert(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SkateFactory2.WebUI.SkateboardService.InsertResponse> SkateFactory2.WebUI.SkateboardService.SkateboardServiceSoap.InsertAsync(SkateFactory2.WebUI.SkateboardService.InsertRequest request) {
            return base.Channel.InsertAsync(request);
        }
        
        public System.Threading.Tasks.Task<SkateFactory2.WebUI.SkateboardService.InsertResponse> InsertAsync(SkateFactory2.WebUI.SkateboardService.Skateboard skateboard) {
            SkateFactory2.WebUI.SkateboardService.InsertRequest inValue = new SkateFactory2.WebUI.SkateboardService.InsertRequest();
            inValue.Body = new SkateFactory2.WebUI.SkateboardService.InsertRequestBody();
            inValue.Body.skateboard = skateboard;
            return ((SkateFactory2.WebUI.SkateboardService.SkateboardServiceSoap)(this)).InsertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SkateFactory2.WebUI.SkateboardService.UpdateResponse SkateFactory2.WebUI.SkateboardService.SkateboardServiceSoap.Update(SkateFactory2.WebUI.SkateboardService.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public void Update(SkateFactory2.WebUI.SkateboardService.Skateboard skateboard) {
            SkateFactory2.WebUI.SkateboardService.UpdateRequest inValue = new SkateFactory2.WebUI.SkateboardService.UpdateRequest();
            inValue.Body = new SkateFactory2.WebUI.SkateboardService.UpdateRequestBody();
            inValue.Body.skateboard = skateboard;
            SkateFactory2.WebUI.SkateboardService.UpdateResponse retVal = ((SkateFactory2.WebUI.SkateboardService.SkateboardServiceSoap)(this)).Update(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SkateFactory2.WebUI.SkateboardService.UpdateResponse> SkateFactory2.WebUI.SkateboardService.SkateboardServiceSoap.UpdateAsync(SkateFactory2.WebUI.SkateboardService.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<SkateFactory2.WebUI.SkateboardService.UpdateResponse> UpdateAsync(SkateFactory2.WebUI.SkateboardService.Skateboard skateboard) {
            SkateFactory2.WebUI.SkateboardService.UpdateRequest inValue = new SkateFactory2.WebUI.SkateboardService.UpdateRequest();
            inValue.Body = new SkateFactory2.WebUI.SkateboardService.UpdateRequestBody();
            inValue.Body.skateboard = skateboard;
            return ((SkateFactory2.WebUI.SkateboardService.SkateboardServiceSoap)(this)).UpdateAsync(inValue);
        }
        
        public void Delete(int skateboardId) {
            base.Channel.Delete(skateboardId);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int skateboardId) {
            return base.Channel.DeleteAsync(skateboardId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SkateFactory2.WebUI.SkateboardService.GetListResponse SkateFactory2.WebUI.SkateboardService.SkateboardServiceSoap.GetList(SkateFactory2.WebUI.SkateboardService.GetListRequest request) {
            return base.Channel.GetList(request);
        }
        
        public SkateFactory2.WebUI.SkateboardService.Skateboard[] GetList(SkateFactory2.WebUI.SkateboardService.ESkateboardCriteria criteria) {
            SkateFactory2.WebUI.SkateboardService.GetListRequest inValue = new SkateFactory2.WebUI.SkateboardService.GetListRequest();
            inValue.Body = new SkateFactory2.WebUI.SkateboardService.GetListRequestBody();
            inValue.Body.criteria = criteria;
            SkateFactory2.WebUI.SkateboardService.GetListResponse retVal = ((SkateFactory2.WebUI.SkateboardService.SkateboardServiceSoap)(this)).GetList(inValue);
            return retVal.Body.GetListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SkateFactory2.WebUI.SkateboardService.GetListResponse> SkateFactory2.WebUI.SkateboardService.SkateboardServiceSoap.GetListAsync(SkateFactory2.WebUI.SkateboardService.GetListRequest request) {
            return base.Channel.GetListAsync(request);
        }
        
        public System.Threading.Tasks.Task<SkateFactory2.WebUI.SkateboardService.GetListResponse> GetListAsync(SkateFactory2.WebUI.SkateboardService.ESkateboardCriteria criteria) {
            SkateFactory2.WebUI.SkateboardService.GetListRequest inValue = new SkateFactory2.WebUI.SkateboardService.GetListRequest();
            inValue.Body = new SkateFactory2.WebUI.SkateboardService.GetListRequestBody();
            inValue.Body.criteria = criteria;
            return ((SkateFactory2.WebUI.SkateboardService.SkateboardServiceSoap)(this)).GetListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SkateFactory2.WebUI.SkateboardService.SearchByIdResponse SkateFactory2.WebUI.SkateboardService.SkateboardServiceSoap.SearchById(SkateFactory2.WebUI.SkateboardService.SearchByIdRequest request) {
            return base.Channel.SearchById(request);
        }
        
        public SkateFactory2.WebUI.SkateboardService.Skateboard SearchById(int skateboardId) {
            SkateFactory2.WebUI.SkateboardService.SearchByIdRequest inValue = new SkateFactory2.WebUI.SkateboardService.SearchByIdRequest();
            inValue.Body = new SkateFactory2.WebUI.SkateboardService.SearchByIdRequestBody();
            inValue.Body.skateboardId = skateboardId;
            SkateFactory2.WebUI.SkateboardService.SearchByIdResponse retVal = ((SkateFactory2.WebUI.SkateboardService.SkateboardServiceSoap)(this)).SearchById(inValue);
            return retVal.Body.SearchByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SkateFactory2.WebUI.SkateboardService.SearchByIdResponse> SkateFactory2.WebUI.SkateboardService.SkateboardServiceSoap.SearchByIdAsync(SkateFactory2.WebUI.SkateboardService.SearchByIdRequest request) {
            return base.Channel.SearchByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SkateFactory2.WebUI.SkateboardService.SearchByIdResponse> SearchByIdAsync(int skateboardId) {
            SkateFactory2.WebUI.SkateboardService.SearchByIdRequest inValue = new SkateFactory2.WebUI.SkateboardService.SearchByIdRequest();
            inValue.Body = new SkateFactory2.WebUI.SkateboardService.SearchByIdRequestBody();
            inValue.Body.skateboardId = skateboardId;
            return ((SkateFactory2.WebUI.SkateboardService.SkateboardServiceSoap)(this)).SearchByIdAsync(inValue);
        }
    }
}
